doc-warnings: true
test-warnings: false
strictness: high
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
python-targets:
  - 3

pylint:
  options:
    max-parents: 15

mccabe:
  run: true

dodgy:
  run: true