doc-warnings: true
test-warnings: false
strictness: veryhigh
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
python-targets:
  - 3

pylint:
  options:
    max-parents=15