# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0005_animalseparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('recommended_age_start', models.IntegerField()),
                ('recommended_age_stop', models.IntegerField()),
                ('dosage_per_kg', models.FloatField()),
                ('grace_period_days', models.IntegerField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dosage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(null=True)),
                ('comments', models.TextField()),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicineapplication',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Treatment'),
        ),
    ]
