# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medicinediscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinediscard',
            name='reason',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
