# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0015_auto_20170624_1312'),
        ('medications', '0003_medication_quantity_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('recovery_time', models.IntegerField()),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.Treatment')),
            ],
        ),
    ]
