# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_auto_20170225_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentry',
            name='weight',
            field=models.FloatField(),
        ),
    ]
