# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0015_auto_20170624_1312'),
        ('feeding', '0005_auto_20170625_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingPeriodForFlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.FeedType')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedingperiodforroom',
            name='feed_type',
        ),
        migrations.RemoveField(
            model_name='feedingperiodforroom',
            name='room',
        ),
        migrations.DeleteModel(
            name='FeedingPeriodForRoom',
        ),
    ]
