# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0007_auto_20170702_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomfeedingchange',
            name='feed_type',
        ),
        migrations.RemoveField(
            model_name='roomfeedingchange',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomFeedingChange',
        ),
    ]
