# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
