# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('buildings', '0003_animalroomentry_animalroomexit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalroomexit',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='animalroomexit',
            name='number_of_animals',
        ),
        migrations.AddField(
            model_name='animalroomexit',
            name='exit_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalroomexit',
            name='exit_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
