# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0005_animalseparation'),
        ('buildings', '0004_auto_20170419_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalroomexit',
            name='exit_id',
        ),
        migrations.RemoveField(
            model_name='animalroomexit',
            name='exit_type',
        ),
        migrations.AddField(
            model_name='animalroomexit',
            name='flock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalroomexit',
            name='number_of_animals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
