# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0005_animalseparation'),
        ('buildings', '0005_auto_20170419_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSeparatedFromRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeathInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.AnimalDeath')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='is_separation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deathinroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Room'),
        ),
        migrations.AddField(
            model_name='animalseparatedfromroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Room'),
        ),
        migrations.AddField(
            model_name='animalseparatedfromroom',
            name='separation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.AnimalSeparation'),
        ),
    ]
