# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0008_auto_20170702_1117'),
        ('buildings', '0008_animalroomexit_farm_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFeedingChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.FeedType')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Room')),
            ],
        ),
    ]
