# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0008_auto_20170702_1117'),
        ('buildings', '0009_roomfeedingchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiloFeedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.FeedEntry')),
            ],
        ),
        migrations.AddField(
            model_name='silo',
            name='feed_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeding.FeedType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silofeedentry',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Silo'),
        ),
    ]
