# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_auto_20170803_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='silofeedentry',
            name='remaining',
            field=models.FloatField(default=0),
        ),
    ]
