# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medication_quantity_unit'),
        ('buildings', '0012_silofeedentry_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryFromRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_room', to='buildings.Room')),
                ('before_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_room', to='buildings.Room')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_room', to='buildings.Room')),
                ('start_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_room', to='buildings.Room')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Treatment')),
            ],
        ),
    ]
