# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_surgery'),
        ('buildings', '0013_surgeryfromroom_treatmentinroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryfromroom',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Surgery'),
        ),
    ]
