# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0004_auto_20170228_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSeparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=250)),
                ('death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.AnimalDeath')),
                ('exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.AnimalExits')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock')),
            ],
        ),
    ]
