# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0006_auto_20170529_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixedFlockAnimalExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='animalexits',
            name='mixed_exit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.MixedFlockAnimalExit'),
        ),
    ]
