# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0009_auto_20170604_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFlockExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.FloatField()),
                ('number_of_animals', models.IntegerField()),
                ('farm_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.AnimalFarmExit')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock')),
            ],
        ),
    ]
