# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0011_remove_animalexits_farm_exit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalfarmexit',
            old_name='total_weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='animalflockexit',
            old_name='total_weight',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='animalseparation',
            name='flockexit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flocks.AnimalFlockExit'),
        ),
        migrations.AddField(
            model_name='animalfarmexit',
            name='destination',
            field=models.CharField(default='Unknown', max_length=140),
        ),
    ]
