# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0013_move_animal_exits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalexits',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='animalseparation',
            name='exit'
        ),
        migrations.RenameField(
            model_name='animalseparation',
            old_name='flockexit',
            new_name='exit'
        ),
        migrations.DeleteModel(
            name='AnimalExits',
        ),
    ]
