# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0014_auto_20170604_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalfarmexit',
            name='number_of_animals',
        ),
        migrations.RemoveField(
            model_name='animalfarmexit',
            name='weight',
        ),
    ]
